apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/dlrkdms125/ARC-RUNNER.git'   # 당신의 저장소
    targetRevision: main
    path: '.'  # values.yaml이 있는 위치
    helm:
      releaseName: actions-runner-controller
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: arc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
 
